import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import "./globals.css";
import MaxWidthWrapper from "@/components/MaxWidthWrapper";
const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MaxWidthWrapper>
          <Navbar />
          <main className="flex flex-col h-[90vh]">
            <div className="flex-1 flex h-full flex-col">

              {children}
            </div>
          </main>
        </MaxWidthWrapper>
      </body>
    </html>
  );
}
